/**
 * Auto-generated by scripts/bootstrapLocales.js
 * Do not edit directly—update JSON files in /locales instead.
 */

window.__LOCALES__ = {
  "de": {
    "meta": {
      "title": "Vibeperform"
    },
    "languageToggle": {
      "label": "Sprache",
      "options": {
        "de": "DE",
        "en": "EN"
      }
    },
    "nav": {
      "brand": "Vibeperform",
      "links": {
        "features": "Funktionen",
        "about": "Ansatz",
        "contact": "Kontakt"
      }
    },
    "hero": {
      "eyebrow": "Intuition + Wirkung",
      "headline": "Verwandle Intuition in messbare Dynamik.",
      "body": "Wir verbinden empathisches Gespür mit präziser KI, damit Ihre Organisation schnell vorankommt, abgestimmt bleibt und Ergebnisse liefert, die Ihre Teams spüren – und Ihre Dashboards belegen.",
      "primaryCta": "Rhythmus starten",
      "secondaryCta": "Ansatz entdecken",
      "visualAriaLabel": "Abstrakte Puls-Grafik"
    },
    "features": {
      "eyebrow": "Was wir freisetzen",
      "headline": "Insights mit menschlichem Gefühl, Wirkung mit messbarer Substanz.",
      "body": "Jedes Mandat verbindet Dialog und Daten, damit Führungskräfte den Puls hören, Teams den Weg sehen und Kennzahlen das Momentum belegen.",
      "cards": [
        {
          "title": "Empathisches Spüren",
          "body": "Dekodieren Sie Team-Stimmungen durch moderierte Interviews mit KI-gestützter Sentiment-Analyse.",
          "callout": "↑ 18 % Team-NPS"
        },
        {
          "title": "Strategische Orchestrierung",
          "body": "Übersetzen Sie Intuition in Roadmaps, Rituale und messbare OKRs, die Ihre Führungskräfte tragen.",
          "callout": "4-wöchiger Alignment-Sprint"
        },
        {
          "title": "Momentum-Dashboards",
          "body": "Machen Sie das Signal-Rausch-Verhältnis sichtbar mit Duotone-Analytics, die Geschichten transportieren.",
          "callout": "92 % Insight-Adoption"
        }
      ]
    },
    "about": {
      "eyebrow": "Warum Vibeperform",
      "headline": "Wir stimmen Strategie mit menschlichem Gespür und maschineller Klarheit ab.",
      "paragraphs": [
        "\"Vibe\" bringt Intuition, Atmosphäre und Empathie. \"Perform\" liefert disziplinierte Ausführung und messbare Ergebnisse. Gemeinsam führen wir Ihre Organisation dazu, mit Herz und Präzision zu handeln.",
        "Von der Diagnose bis zur Umsetzung arbeiten unsere Consultants direkt mit Ihren Teams, kombinieren moderierte Workshops mit intelligenten Copiloten und halten Momentum sichtbar."
      ],
      "highlights": [
        {
          "title": "Hybrid-Intelligence-Labs",
          "body": "Interaktive Sessions, die menschliche Nuancen freilegen, während KI verwertbare Daten erfasst."
        },
        {
          "title": "Rhythmusgestaltung",
          "body": "Wir formen Rituale, Stand-ups und Reviews, die Tempo halten ohne auszubrennen."
        },
        {
          "title": "Nachweis von Momentum",
          "body": "Scorecards erzählen jede Story in Narrativ und Zahlen für jeden Stakeholder."
        }
      ]
    },
    "contact": {
      "eyebrow": "Bereit zum Abgleich",
      "headline": "Starten Sie den Rhythmus mit einer KI-Strategie-Session.",
      "body": "Teilen Sie Ihre aktuelle Herausforderung und wir entwerfen einen Signal-Scan, der Quick Wins, Risiken und erste Hebel sichtbar macht.",
      "primaryCta": "Discovery-Call buchen",
      "secondaryCta": "Unseren Rhythmus ansehen"
    },
    "footer": {
      "brand": "Vibeperform",
      "links": {
        "features": "Funktionen",
        "about": "Ansatz",
        "contact": "Kontakt"
      },
      "legal": "Vibeperform. Alle Rechte vorbehalten."
    }
  },
  "en": {
    "meta": {
      "title": "Vibeperform"
    },
    "languageToggle": {
      "label": "Language",
      "options": {
        "de": "DE",
        "en": "EN"
      }
    },
    "nav": {
      "brand": "Vibeperform",
      "links": {
        "features": "Features",
        "about": "Approach",
        "contact": "Contact"
      }
    },
    "hero": {
      "eyebrow": "Intuition + Impact",
      "headline": "Turn intuition into measurable momentum.",
      "body": "We blend empathetic sensing with precision AI so your organisation can move fast, stay aligned, and deliver outcomes your teams feel—and your dashboards prove.",
      "primaryCta": "Start the cadence",
      "secondaryCta": "Explore the approach",
      "visualAriaLabel": "Abstract pulse graphic"
    },
    "features": {
      "eyebrow": "What we unlock",
      "headline": "Insight that feels human, impact that stacks up.",
      "body": "Every engagement bridges conversation with computation—so leaders hear the pulse, teams see the path, and the metrics prove the momentum.",
      "cards": [
        {
          "title": "Empathic sensing",
          "body": "Decode team vibes through guided interviews enriched with AI sentiment lenses.",
          "callout": "↑ 18% team NPS"
        },
        {
          "title": "Strategic orchestration",
          "body": "Translate intuition into roadmaps, rituals, and measurable OKRs your leaders own.",
          "callout": "4-week alignment sprint"
        },
        {
          "title": "Momentum dashboards",
          "body": "Surface live signal-to-noise ratios with duotone analytics built for narrative.",
          "callout": "92% insight adoption"
        }
      ]
    },
    "about": {
      "eyebrow": "Why Vibeperform",
      "headline": "We tune strategy with human sense and machine clarity.",
      "paragraphs": [
        "“Vibe” brings intuition, atmosphere, and empathy. “Perform” brings disciplined execution and measurable outcomes. Together, we guide your organisation to act with both heart and precision.",
        "From diagnostics to delivery, our consultants embed alongside your teams, pairing guided workshops with intelligent copilots that keep momentum visible."
      ],
      "highlights": [
        {
          "title": "Hybrid intelligence labs",
          "body": "Interactive sessions that surface human nuance while AI captures actionable data."
        },
        {
          "title": "Cadence design",
          "body": "We shape rituals, standups, and reviews that sustain rhythm without burnout."
        },
        {
          "title": "Proof of traction",
          "body": "Scorecards articulate the story in both narrative and numbers for every stakeholder."
        }
      ]
    },
    "contact": {
      "eyebrow": "Ready to sync",
      "headline": "Start the cadence with an AI strategy session.",
      "body": "Share your current challenge and we will design a signal scan to reveal quick wins, key risks, and which levers to pull first.",
      "primaryCta": "Book discovery call",
      "secondaryCta": "View our rhythm"
    },
    "footer": {
      "brand": "Vibeperform",
      "links": {
        "features": "Features",
        "about": "Approach",
        "contact": "Contact"
      },
      "legal": "Vibeperform. All rights reserved."
    }
  }
};
